### ISSUE TITLE
Add map function to display

### ISSUE THREAD

**Issue by nguy** [nguy/artview#114]
One feature that would be nice to add would be to plot on a basemap using Py-ART `RadarMapDisplay` and `GridMapDisplay`. One caveat is that this only works on PPI or Sector scans. So checks need to be done on `plot_type`.

There are a couple different approaches that could be taken. These are the ones I've considered thus far:
1. Duplicate `plot_radar/plot_grid` to `plot_radar_map/plot_grid_map` and make necessary changes. Make this a potential mode.
2. Add to existing `plot_radar` as an `Add Map` feature in Display drop down.
3. Add to existing `plot_radar` as a separate class (not substantially different than point 1).
3. Set this up as a Plugin. Still requires one of the three points.

There are a few more functions/variables to track so this would increase the size of `plot_radar code` if added. Thoughts?

**Comment by gamaanderson** [comment]
Grid plot already uses `GridMapDisplay` the issue is actually only with radar.

Actually I think plot_radar only uses a relative limited subset of what pyart offers (independent of map or not), mainly airborne has some other plot options that we don't cover. This has been an issue in my mind for some time now, but it never got to the top of my list.

To choose between your options is less of a question what pyart class/function we are using, and more a question of how many control mechanisms we want to offer. Unfortunately I have no clear vision in my mind, so I can't really make a choice.

**Comment by nguy** [comment]
Very good. We currently only use what is necessary from Py-ART RadarDisplay, which was purposeful at the beginning to give flexibility to how we handled figures for the display.

I'm going to begin by adding this into ```plot_radar``` and experiment with the two separate ideas there. I'll take a look at ```plot_grid``` again to see how you handled this. One potential problem could be the interface with limits, etc. We'll see how it goes.

**Comment by gamaanderson** [comment]
you are right, limits is a problem, basemap was made a pretty bad work on that part (I've seen the source code!)

**Comment by gamaanderson** [comment]
so, adding a map, in special a topography map, shall happen using the `basemap` instance of the pyart `mapDisplay` class. Now is the question if we do this in the display or in a pluging. The first will implies an significant new part of the Display class and even a new **plot_.py** file, that I would like to avoid, the second implies making the display attribute, or an equivalent, shared and this is also some what inconvenient. thoughts?

**Comment by nguy** [comment]
So I've been thinking a lot about this. Given how slow the PyART RadarMapDisplay is, I don't think using this is a good idea. The slow speed stems from the basemap portion. I would prefer to create a map image that could be placed underneath the radar image. This way we wouldn't have to render the map every time anything was changed. 

A caveat to this is that the user would have to be aware that the map was made with whatever data file. If they switch radars or having a moving coordinate system, then this could become an incorrect map image. This is tougher than I initially believed. 

I think providing a plugin that adds a map image and could be "locked" as you put forth with cmap might be a good way to go. We'd just need to make it clear in the documentation of the potential issues. Now would this require that the map instance be potentially shared? I don't know if that is a good idea. But I also am not fond of putting this in the display class....

**Comment by nguy** [comment]
Thinking aloud: Maybe a plugin where one could select the Display to use and build a map. And then turn on/off said map by toggling check box. It may not be elegant, but it would do the trick?

**Comment by gamaanderson** [comment]
I did not knew RadarMapDisplay was slow, specially considering GridMapDisplay is ok.

**Comment by nguy** [comment]
Well admittedly, slow is relative. It's fine for producing figures, but currently the map is generated each time the plot is called. So this makes using this from an operational standpoint (i.e. scrolling through files) not an optimal experience.

**Comment by gamaanderson** [comment]
Developing the possibility of using map display and add a background based in a file. Here is an image
![](https://cloud.githubusercontent.com/assets/7915525/16899987/757fbda8-4c16-11e6-9fb3-a5d376534751.png)
The resolution is a bad because the file I'm using is a global 0.1 deg. To improve that one would need to go after better data and put in a similar format. The reason I'm using this file is because it is global and public available direct from a http

I still have to work in the grid, after that I will upload the branch.

**Comment by gamaanderson** [comment]
should I check this as done in issue #135?

**Comment by nguy** [comment]
I think so. Anything further would be an update.

**Comment by gamaanderson** [comment]
can this be closed?

**Comment by nguy** [comment]
Yes, I'd like to reopen this in the future when there is a feasible option. Currently I don't believe there is a robust way of doing this.
